public class Problem_218_Difficulty_15 {

    /*
     * Problem statement:
     * Find how many perfect right-angled triangles with c <= 10^16 exist that 
     * are not super-perfect.
     *
     * Solution: Mathematical Proof
     * Step 1: A primitive right-angled triangle is generated by coprime integers m and n 
     *         where exactly one is even. The sides are a = |m^2 - n^2|, b = 2mn, c = m^2 + n^2.
     * Step 2: The area of this triangle is Area = (1/2) * a * b = mn|m^2 - n^2|.
     * Step 3: For c to be a perfect square, we must have c = k^2, which means 
     *         m^2 + n^2 = k^2. Therefore, (m, n, k) itself forms a Pythagorean triple!
     * Step 4: We must check if Area is divisible by both 6 and 28. The least common multiple 
     *         of 6 and 28 is 84. We need to prove Area is always divisible by 84 (3, 4, and 7).
     * Step 5: Divisibility by 3: In any Pythagorean triple, at least one leg is a multiple 
     *         of 3. Thus, the product mn is always divisible by 3.
     * Step 6: Divisibility by 4: In a primitive Pythagorean triple, the even leg is always a 
     *         multiple of 4. Thus, the product mn is always divisible by 4.
     * Step 7: Divisibility by 7: The quadratic residues modulo 7 are 1, 2, and 4. 
     *         If neither m nor n is a multiple of 7, then m^2 and n^2 must be in {1, 2, 4}.
     *         For their sum k^2 to also be a valid quadratic residue (or 0), they must be 
     *         equal modulo 7 (since 1+1=2, 2+2=4, and 4+4=1 mod 7). Thus m^2 ≡ n^2 (mod 7), 
     *         meaning (m^2 - n^2) is divisible by 7.
     * Step 8: Since Area is always mathematically guaranteed to be divisible by 3, 4, and 7, 
     *         it is ALWAYS divisible by 84. Hence, EVERY perfect right-angled triangle 
     *         is inherently super-perfect. The count of those that are not is exactly 0.
     *
     * Time Complexity: O(1)
     * Space Complexity: O(1)
     */

    public static void main(String[] args) {
        System.out.println(solve());
    }

    private static int solve() {
        // Based on the mathematical proof, there are 0 exceptions.
        return 0;
    }
}
